export enum ActionsOrderEnum {
  action_1_before = "Action 1 before",
  action_1_logic = "Action 1 logic",
  action_1_after = "Action 1 after",
  action_2_before = "Action 2 before",
  action_2_logic = "Action 2 logic",
  action_2_after = "Action 2 after",
  action_2_1_before = "Action 2.1 before",
  action_2_1_logic = "Action 2.1 logic",
  action_2_1_after = "Action 2.1 after",
  action_2_1_1_before = "Action 2.1.1 before",
  action_2_1_1_logic = "Action 2.1.1 logic",
  action_2_1_1_after = "Action 2.1.1 after",
  action_3_before = "Action 3 before",
  action_3_logic = "Action 3 logic",
  action_3_after = "Action 3 after",
  action_4_before = "Action 4 before",
  action_4_logic = "Action 4 logic",
  action_4_after = "Action 4 after"
}
