version: "3"
services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
      - storage:/verdaccio/storage
      - conf:/verdaccio/conf
volumes:
  storage:
    driver: local
  conf:
    driver: local
