version: "3.8"
services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
      - storage:/verdaccio/storage
      - conf:/verdaccio/conf
  cli:
    build:
      context: ../dockerfile
      dockerfile: Dockerfile.build
    volumes:
      - ../../../../:/app
    environment:
      - TSCONFIG=./projects/apps/cli/tsconfig.prod.json
      - PACKAGE=./projects/apps/cli/package.json
      - OUTPUT=./dist/cli
    depends_on:
      - verdaccio
  jest:
    build:
      context: ../dockerfile
      dockerfile: Dockerfile.build
    volumes:
      - ../../../../:/app
    environment:
      - TSCONFIG=./projects/libs/module/jest/tsconfig.prod.json
      - PACKAGE=./projects/libs/module/jest/package.json
      - OUTPUT=./dist/jest
    depends_on:
      - verdaccio
volumes:
  storage:
  conf:
