version: "3.8"
services:
  cli_build:
    build:
      context: ../../../../
      dockerfile: ./projects/tools/docker/dockerfile/strategy/Dockerfile.build
    container_name: cli_build
    volumes:
      - ../../../../:/app
    environment:
      - TSCONFIG=./projects/apps/cli/tsconfig.dev.json
      - PACKAGE=./projects/apps/cli/package.json
      - OUTDIR=./dist/cli
  remove_dist:
    build:
      context: ../../../../
      dockerfile: ./projects/tools/docker/dockerfile/strategy/Dockerfile.remove-dist
    container_name: remove_dist
    volumes:
      - ../../../../:/app
