version: "3.8"
services:
  cli_build:
    build:
      context: ../dockerfile
      dockerfile: Dockerfile.build
    volumes:
      - ../../../../:/app
    environment:
      - TSCONFIG=./projects/apps/cli/tsconfig.prod.json
      - PACKAGE=./projects/apps/cli/package.json
      - OUTPUT=./dist/cli
  jest_build:
    build:
      context: ../dockerfile
      dockerfile: Dockerfile.build
    volumes:
      - ../../../../:/app
    environment:
      - TSCONFIG=./projects/libs/module/jest/tsconfig.prod.json
      - PACKAGE=./projects/libs/module/jest/package.json
      - OUTPUT=./dist/jest
