version: "3.8"
services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
      - ./config:/verdaccio/conf
      - ./storage:/verdaccio/storage
  cli_build:
    build:
      context: ../../../../
      dockerfile: ./projects/tools/docker/dockerfile/strategy/Dockerfile.build
    volumes:
      - ../../../../:/app
    environment:
      - TSCONFIG=./projects/apps/cli/tsconfig.prod.json
      - PACKAGE=./projects/apps/cli/package.json
      - OUTDIR=./dist/cli
      - TEST=./dist/cli/projects/apps/cli/src/main.js
  jest_build:
    build:
      context: ../../../../
      dockerfile: ./projects/tools/docker/dockerfile/strategy/Dockerfile.build
    volumes:
      - ../../../../:/app
    environment:
      - TSCONFIG=./projects/libs/module/jest/tsconfig.prod.json
      - PACKAGE=./projects/libs/module/jest/package.json
      - OUTDIR=./dist/jest
      - TEST=./dist/jest/projects/libs/module/jest/src/main.js
volumes:
  config:
  storage:
