FROM ubuntu:24.04

WORKDIR /app

RUN apt update
RUN apt install wget -y
RUN apt install npm -y
RUN npm i -g typescript
RUN npm i -g tsc-alias

RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -

CMD ["sh", "./projects/tools/docker/shell/build.sh"]
